export const FETCH_STOCK_LIST_REQUEST = 'FETCH_STOCK_LIST_REQUEST';
export const FETCH_STOCK_LIST_SUCCESS = 'FETCH_STOCK_LIST_SUCCESS';
export const FETCH_STOCK_LIST_FAILURE = 'FETCH_STOCK_LIST_FAILURE';

export const FETCH_TOP_50_STOCKS_REQUEST = 'FETCH_TOP_50_STOCKS_REQUEST';
export const FETCH_TOP_50_STOCKS_SUCCESS = 'FETCH_TOP_50_STOCKS_SUCCESS';
export const FETCH_TOP_50_STOCKS_FAILURE = 'FETCH_TOP_50_STOCKS_FAILURE';

export const FETCH_MARKET_CHART_REQUEST = 'FETCH_MARKET_CHART_REQUEST';
export const FETCH_MARKET_CHART_SUCCESS = 'FETCH_MARKET_CHART_SUCCESS';
export const FETCH_MARKET_CHART_FAILURE = 'FETCH_MARKET_CHART_FAILURE';

export const FETCH_STOCK_BY_SYMBOL_REQUEST = 'FETCH_STOCK_BY_SYMBOL_REQUEST';
export const FETCH_STOCK_BY_SYMBOL_SUCCESS = 'FETCH_STOCK_BY_SYMBOL_SUCCESS';
export const FETCH_STOCK_BY_SYMBOL_FAILURE = 'FETCH_STOCK_BY_SYMBOL_FAILURE';

export const SEARCH_STOCK_REQUEST = 'SEARCH_STOCK_REQUEST';
export const SEARCH_STOCK_SUCCESS = 'SEARCH_STOCK_SUCCESS';
export const SEARCH_STOCK_FAILURE = 'SEARCH_STOCK_FAILURE';
